export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const API_FETCH_START = 'API_FETCH_START';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAIL = 'SIGNIN_USER_FAIL';
